stages:
- name: compile
  steps:
  - runScriptConfig:
      image: 192.168.72.3:11080/library/maven:3.6.0-jdk-8-alpine
      shellScript: mvn clean package -Dmaven.test.skip=true
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: sangrei/springbootdemo:v0.1
      pushRemote: true
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
