stages:
- name: compile
  steps:
  - runScriptConfig:
      image: 192.168.72.3:11080/library/maven:3.6.0-jdk-8-alpine
      shellScript: mvn clean package
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: springbootdemo
      registry: 192.168.72.3:11080
  - env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
