stages:
- name: compile
  steps:
  - runScriptConfig:
      image: 192.168.72.3:11080/library/maven
      shellScript: mvn clean package
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: library/springbootdemo:v1
      pushRemote: true
      registry: 192.168.72.3:11080
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 1
